apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service2.labels" . | nindent 4 }}
data:
  SERVICE1_URL: {{ .Values.config.service1URL | quote }}
